# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: adapter_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='adapter_service.proto',
  package='adapater',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x15\x61\x64\x61pter_service.proto\x12\x08\x61\x64\x61pater\"6\n\rBlockInterval\x12\x11\n\topen_time\x18\x01 \x01(\x03\x12\x12\n\nclose_time\x18\x02 \x01(\x03\"5\n\x0cUnixInterval\x12\x11\n\topen_time\x18\x01 \x01(\x03\x12\x12\n\nclose_time\x18\x02 \x01(\x03\"\x89\x01\n\x06Rating\x12\x11\n\tchannelId\x18\x01 \x01(\x03\x12\r\n\x05nonce\x18\x02 \x01(\x03\x12\x10\n\x08\x63onsumer\x18\x03 \x01(\t\x12\x10\n\x08provider\x18\x04 \x01(\t\x12)\n\x08interval\x18\x05 \x01(\x0b\x32\x17.adapater.BlockInterval\x12\x0e\n\x06\x61mount\x18\x06 \x01(\x03\"2\n\rRatingSummary\x12!\n\x07ratings\x18\x01 \x03(\x0b\x32\x10.adapater.Rating2O\n\rRatingService\x12>\n\nGetRatings\x12\x17.adapater.BlockInterval\x1a\x17.adapater.RatingSummaryb\x06proto3')
)




_BLOCKINTERVAL = _descriptor.Descriptor(
  name='BlockInterval',
  full_name='adapater.BlockInterval',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='open_time', full_name='adapater.BlockInterval.open_time', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='close_time', full_name='adapater.BlockInterval.close_time', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=89,
)


_UNIXINTERVAL = _descriptor.Descriptor(
  name='UnixInterval',
  full_name='adapater.UnixInterval',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='open_time', full_name='adapater.UnixInterval.open_time', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='close_time', full_name='adapater.UnixInterval.close_time', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=144,
)


_RATING = _descriptor.Descriptor(
  name='Rating',
  full_name='adapater.Rating',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='channelId', full_name='adapater.Rating.channelId', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nonce', full_name='adapater.Rating.nonce', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='consumer', full_name='adapater.Rating.consumer', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='provider', full_name='adapater.Rating.provider', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='interval', full_name='adapater.Rating.interval', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount', full_name='adapater.Rating.amount', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=147,
  serialized_end=284,
)


_RATINGSUMMARY = _descriptor.Descriptor(
  name='RatingSummary',
  full_name='adapater.RatingSummary',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ratings', full_name='adapater.RatingSummary.ratings', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=286,
  serialized_end=336,
)

_RATING.fields_by_name['interval'].message_type = _BLOCKINTERVAL
_RATINGSUMMARY.fields_by_name['ratings'].message_type = _RATING
DESCRIPTOR.message_types_by_name['BlockInterval'] = _BLOCKINTERVAL
DESCRIPTOR.message_types_by_name['UnixInterval'] = _UNIXINTERVAL
DESCRIPTOR.message_types_by_name['Rating'] = _RATING
DESCRIPTOR.message_types_by_name['RatingSummary'] = _RATINGSUMMARY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BlockInterval = _reflection.GeneratedProtocolMessageType('BlockInterval', (_message.Message,), dict(
  DESCRIPTOR = _BLOCKINTERVAL,
  __module__ = 'adapter_service_pb2'
  # @@protoc_insertion_point(class_scope:adapater.BlockInterval)
  ))
_sym_db.RegisterMessage(BlockInterval)

UnixInterval = _reflection.GeneratedProtocolMessageType('UnixInterval', (_message.Message,), dict(
  DESCRIPTOR = _UNIXINTERVAL,
  __module__ = 'adapter_service_pb2'
  # @@protoc_insertion_point(class_scope:adapater.UnixInterval)
  ))
_sym_db.RegisterMessage(UnixInterval)

Rating = _reflection.GeneratedProtocolMessageType('Rating', (_message.Message,), dict(
  DESCRIPTOR = _RATING,
  __module__ = 'adapter_service_pb2'
  # @@protoc_insertion_point(class_scope:adapater.Rating)
  ))
_sym_db.RegisterMessage(Rating)

RatingSummary = _reflection.GeneratedProtocolMessageType('RatingSummary', (_message.Message,), dict(
  DESCRIPTOR = _RATINGSUMMARY,
  __module__ = 'adapter_service_pb2'
  # @@protoc_insertion_point(class_scope:adapater.RatingSummary)
  ))
_sym_db.RegisterMessage(RatingSummary)



_RATINGSERVICE = _descriptor.ServiceDescriptor(
  name='RatingService',
  full_name='adapater.RatingService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=338,
  serialized_end=417,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetRatings',
    full_name='adapater.RatingService.GetRatings',
    index=0,
    containing_service=None,
    input_type=_BLOCKINTERVAL,
    output_type=_RATINGSUMMARY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_RATINGSERVICE)

DESCRIPTOR.services_by_name['RatingService'] = _RATINGSERVICE

# @@protoc_insertion_point(module_scope)
